### ISSUE TITLE
Target SDK version 31 requires a minimum of signature scheme v2

### ISSUE THREAD

**Issue by thenderson55** [bitrise-steplib/steps-google-play-deploy#140]
- Which version of the step is effected? 3.7.2
- Is the issue reproducible with the latest version? YES 
- Does the issue happen sporadically, or every time? EVERY TIME

- Build URL: https://app.bitrise.io/build/d22ce9b0-f43c-4511-bb2c-8ecc2c8c9412#?tab=log

To get my React Native Android app to build locally, in  ```android/build.gradle``` I needed to upgrade:

```
compileSdkVersion = 29  ->  31
targetSdkVersion = 29  ->  31
```

In Bitrise, my build now fails at ```google-play-deploy ( version 3.7.2 )``` with this message:

```
Upload apks or app bundles
Uploading /Users/vagrant/deploy/app-[REDACTED]-bitrise-signed.apk 1/1

Failed to upload application(s): failed to upload apk, error: googleapi: 
Error 403: APK signature is invalid or does not exist. Error from apksigner:
ERROR: MIN_SIG_SCHEME_FOR_TARGET_SDK_NOT_MET: 
Target SDK version 31 requires a minimum of signature scheme v2; 
the APK is not signed with this or a later signature scheme, forbidden
```
I tried adding ```v2SigningEnabled true``` in ```android/app/build.gradle``` signingConfigs but it didn't change anything. 

Also tried with targeting sdk version 30 but it failed similar to 29 - ```Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.```

Any advice on how to fix this?

**Comment by thenderson55** [comment]
I fixed it.

In “Android sign” workflow step, change “Enables apksigner“ to true.

Also may need to add ```android:exported="false"``` to plugins using ```intent-filter``` in the AndroidManifest.xml.

See answer here:

https://stackoverflow.com/questions/70695372/you-uploaded-an-apk-or-android-app-bundle-which-has-an-activity-activity-alias

**Comment by yitelu** [comment]
I’ve encountered the scenario of error failed to upload application(s): failed to upload apk, error: googleapi: Error 403: APK signature is invalid or does not exist

This is how I solved the error with my approach and my app is deployed to GooglePlayStore via the Bitrise CICD deployment successfully.

1. The initial app/build.gradle config was set targetSdk 32 and then I changed to targetSdk 30
2. Originally my app was published in AAB instead of APK, the default build type is APK in Bitrise workflow Android Build, so I changed that build type to AAB
3. Then I was successfully auto deploy to GooglePlayStore production channel via Bitrise CICD 

![Screen Shot 2022-06-17 at 10 57 26 AM](https://user-images.githubusercontent.com/3092219/174352873-f56cb849-70cb-4bdf-a6aa-6c1b673566cc.png)
