### ISSUE TITLE
Failed to upload APKs: failed to upload apk, error: googleapi: Error 403: APK is not a valid ZIP archive, forbidden

### ISSUE THREAD

**Issue by SaravanarajaGITHUB** [bitrise-steplib/steps-google-play-deploy#89]
Facing this issue, no solution found in net & also with this related issue link too #86 

Build URL  --> [https://app.bitrise.io/build/b0b1aaa5b60b9dd5#?tab=log](Link)

![Capture](https://user-images.githubusercontent.com/6235704/87006336-2243f180-c1de-11ea-8c69-98f53a5ca2eb.PNG)

**Comment by lucasfronza** [comment]
Facing the same issue

**Comment by jgersonde** [comment]
Same issue !!!!!

**Comment by ibushi-gs** [comment]
Facing the same issue.

**Comment by fwvictor** [comment]
Same issue!!

**Comment by srikanthreddi4u** [comment]
facing the same issue , any update?

**Comment by david-alejandro-reyes-milian** [comment]
same here, obviously something changed in the store. Checking out

**Comment by SergiyDivnych** [comment]
Same issue!!

**Comment by dfabulich** [comment]
There's a substantial discussion about this on the [fastlane issue](https://github.com/fastlane/fastlane/issues/16721). The fastlane developer reached out to Google and had confirmation that it's a known issue. Follow that thread for more status updates.

**Comment by tuanta429** [comment]
Same here!

**Comment by jamesjara** [comment]
we are having the same problem

**Comment by sonny-kava-up** [comment]
+1

**Comment by bitce** [comment]
Hi everyone!

Sorry for the silence on this issue so far. As @dfabulich mentioned, the issue seems to be related to the Google Play store and has an intermittent nature - I have several users confirming that deployment works as expected by now.

What's important is that this issue only affects APKs and is only happening when using their API. So uploading a release manually or deploying bundles should work. 

We're still looking into what's happening exactly, will keep everyone updated here.
